<?php

namespace AppBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    public function showLastFive()
    {
        $em     = $this->getEntityManager();
        $query  = $em->createQuery("SELECT l FROM AppBundle:Location l
                                          ORDER BY l.id DESC ");
        $query->setMaxResults(5);

        $result = $query->getResult();
        return $result;
    }
}
